### ISSUE TITLE
R1 Clarification

### ISSUE THREAD

**Issue by JayCanuck** [Helder1981/BK-GBC#1]
Just looking at the LCD board I noticed the R1 spot on the back and just wanted to ask clarification on what would go there. A 3.9 Ohm resistor? Thanks!

**Comment by Helder1981** [comment]
Yes 3.9 ohm resistor goes there, if you open the schematic in EagleCad it will show you what it is as well.

**Comment by JayCanuck** [comment]
Awesome, thanks!
